Changes to SnappyData yaml file. - Set proper data directory. - Correct the PreStop hook - Removed random sleeps while starting servers/lead. Instead waiting for locator to be accessible.

diff --git a/snappydata-cluster.yml b/snappydata-cluster.yml
--- a/snappydata-cluster.yml
+++ b/snappydata-cluster.yml
@@ -18,10 +18,21 @@ spec:
   - port: 1527
     targetPort: 1527
     name: jdbc
+  type: LoadBalancer
+  selector:
+    app: snappydata-locator
+---
+apiVersion: v1
+kind: Service
+metadata:
+  name: snappydata-locator-internal
+  labels:
+    app: snappydata
+spec:
+  ports:
   - port: 10334
     targetPort: 10334
     name: locator-clustering-endpoint
-  type: LoadBalancer
   selector:
     app: snappydata-locator
 ---
@@ -76,9 +87,9 @@ spec:
         image: snappydatainc/snappydata:1.0.0
         imagePullPolicy: IfNotPresent
         resources:
-        requests:
-          memory: "1024Mi"
-#         cpu: "200m"
+          requests:
+            memory: "1024Mi"
+#           cpu: "200m"
         ports:
         - containerPort: 10334
           name: locator
@@ -89,19 +100,34 @@ spec:
           tcpSocket:
             port: 1527
           initialDelaySeconds: 80
-        command: ["/bin/bash", "-c"]
-        args: ["start locator"]
+        command: 
+          - "/bin/bash"
+          - "-c"
+          - >
+            cat /etc/passwd > /tmp/passwd;
+            echo "$(id -u):x:$(id -u):$(id -g):dynamic uid:/opt/snappydata:/bin/false" >> /tmp/passwd;
+
+            export NSS_WRAPPER_PASSWD=/tmp/passwd;
+            export NSS_WRAPPER_GROUP=/etc/group;
+            export LD_PRELOAD=/usr/lib64/libnss_wrapper.so;
+
+            echo "starting sshd service";
+            service sshd start;
+
+            hname=`hostname`;
+            workdir="/opt/snappydata/work/$hname";
+            mkdir -p "$workdir";
+            echo "$hname  -dir=$workdir" > /opt/snappydata/conf/locators;
+            /opt/snappydata/sbin/snappy-locators.sh start;
+            tail -f /dev/null;
         lifecycle:
           preStop:
             exec:
-              command:
-              - /opt/snappydata/sbin/snappy-locators.sh stop
+              command: ["/opt/snappydata/sbin/snappy-locators.sh", "stop"]
         volumeMounts:
         - mountPath: "/opt/snappydata/work"
           name: snappy-disk-claim
 
-  terminationGracePeriodSeconds: 60
-  
   volumeClaimTemplates:
   - metadata:
       name: snappy-disk-claim
@@ -147,19 +173,46 @@ spec:
         livenessProbe:
           tcpSocket:
             port: 1527
-          initialDelaySeconds: 160
-        command: ["/bin/bash", "-c"]
-        args: ["sleep 15; start server -locators=snappydata-locator:10334 -client-port=1527 -J-Dgemfirexd.hostname-for-clients=snappydata-server-public ; sleep 10000000"]
+#         initial delay intentionally kept large, as server waits(250 seconds) for locator to be available
+          initialDelaySeconds: 360
+        command:
+          - "/bin/bash"
+          - "-c"
+          - >
+            yum -y install nc && yum clean all -y;
+
+            COUNTER=0;
+            while ! nc -z snappydata-locator-internal 10334 > /dev/null 2>&1; do
+              echo "Waiting for locator to be online";
+              sleep 5;
+              let COUNTER=COUNTER+1 ;
+              if [ $COUNTER -eq 50 ]; then echo "ERROR: Locator is not up"; exit 1; fi;
+            done;
+
+            cat /etc/passwd > /tmp/passwd;
+            echo "$(id -u):x:$(id -u):$(id -g):dynamic uid:/opt/snappydata:/bin/false" >> /tmp/passwd;
+
+            export NSS_WRAPPER_PASSWD=/tmp/passwd;
+            export NSS_WRAPPER_GROUP=/etc/group;
+            export LD_PRELOAD=/usr/lib64/libnss_wrapper.so;
+
+            echo "starting sshd service";
+            service sshd start;
+
+            hname=`hostname`;
+            workdir="/opt/snappydata/work/$hname";
+            mkdir -p "$workdir";
+            echo "$hname -locators=snappydata-locator-internal:10334 -client-port=1527 -dir=$workdir" > /opt/snappydata/conf/servers;
+            /opt/snappydata/sbin/snappy-servers.sh start;
+            tail -f /dev/null;
         lifecycle:
           preStop:
             exec:
-              command:
-              - /opt/snappydata/sbin/snappy-servers.sh stop
+              command: ["/opt/snappydata/sbin/snappy-servers.sh", "stop"]
         volumeMounts:
         - mountPath: "/opt/snappydata/work"
           name: snappy-disk-claim
-      terminationGracePeriodSeconds: 60
-  
+
   volumeClaimTemplates:
   - metadata:
       name: snappy-disk-claim
@@ -204,19 +257,46 @@ spec:
           httpGet:
             path: /
             port: 5050
-          initialDelaySeconds: 160
-        command: ["/bin/bash", "-c"]
-        args: ["sleep 15; start lead -locators=snappydata-locator:10334 ; sleep 1000000"]
+#         initial delay intentionally kept large, as lead waits(250 seconds) for servers to be available
+          initialDelaySeconds: 360
+        command: 
+          - "/bin/bash"
+          - "-c"
+          - >
+            yum -y install nc && yum clean all -y;
+
+            COUNTER=0;
+            while ! nc -z snappydata-server 1527 > /dev/null 2>&1; do
+              echo "Waiting for servers to be online";
+              sleep 5;
+              let COUNTER=COUNTER+1 ;
+              if [ $COUNTER -eq 50 ]; then echo "ERROR: Servers are not up"; exit 1; fi;
+            done;
+
+            cat /etc/passwd > /tmp/passwd;
+            echo "$(id -u):x:$(id -u):$(id -g):dynamic uid:/opt/snappydata:/bin/false" >> /tmp/passwd;
+
+            export NSS_WRAPPER_PASSWD=/tmp/passwd;
+            export NSS_WRAPPER_GROUP=/etc/group;
+            export LD_PRELOAD=/usr/lib64/libnss_wrapper.so;
+
+            echo "starting sshd service";
+            service sshd start;
+
+            hname=`hostname`;
+            workdir="/opt/snappydata/work/$hname";
+            mkdir -p "$workdir";
+            echo "$hname -locators=snappydata-locator-internal:10334 -dir=$workdir" > /opt/snappydata/conf/leads;
+            /opt/snappydata/sbin/snappy-leads.sh start;
+            tail -f /dev/null;
         lifecycle:
           preStop:
             exec:
-              command:
-              - /opt/snappydata/sbin/snappy-leads.sh stop
+              command: ["/opt/snappydata/sbin/snappy-leads.sh", "stop"]
         volumeMounts:
         - mountPath: "/opt/snappydata/work"
           name: snappy-disk-claim
-      terminationGracePeriodSeconds: 60
-  
+
   volumeClaimTemplates:
   - metadata:
       name: snappy-disk-claim
